// Generated by the release identity gate. The generator deliberately excludes
// this file from the source-tree digest to avoid a self-referential hash.
export const EFFECTIME_EDGE_SOURCE_TREE_SHA256 =
  "d83d4ed7e58d0e112afc5b37c1c86ba509510f40f30b1f27a2608f9b25e024f4" as const;
