// Generated by the release identity gate. The generator deliberately excludes
// this file from the source-tree digest to avoid a self-referential hash.
export const EFFECTIME_EDGE_SOURCE_TREE_SHA256 =
  "291952ecc981746015e04e125ad7d4d1636563539f6b7d3d8b50477fe889044c" as const;
