// Generated by the release identity gate. The generator deliberately excludes
// this file from the source-tree digest to avoid a self-referential hash.
export const EFFECTIME_EDGE_SOURCE_TREE_SHA256 =
  "060c81afd019ce1decc063de5ea887ec343899ca1f5821cd30bd32c012df5150" as const;
