INSERT INTO public.features (feature_key, name, module, description, fiscal_weight, dependencies, metadata) VALUES
('attendance_log','Munkaóra naplózás','attendance','Időnyilvántartás.',9,ARRAY['members_list']::text[],'{"feature_id": "TA-001", "necessity": "required", "value_score": "9", "estimated_dev_cost": "L", "created_in_version": "3.6.0", "current_status": "public"}'::jsonb),
('attendance_oncall','On-call ügyelet','attendance','24/7 csapatok.',7,ARRAY['attendance_log']::text[],'{"feature_id": "TA-002", "necessity": "optional", "value_score": "7", "estimated_dev_cost": "M", "created_in_version": "3.6.0", "current_status": "public"}'::jsonb),
('attendance_periods','Időszak workflow','attendance','Hónap zárás.',8,ARRAY['attendance_log']::text[],'{"feature_id": "TA-003", "necessity": "required", "value_score": "8", "estimated_dev_cost": "M", "created_in_version": "3.6.0", "current_status": "public"}'::jsonb),
('payroll_export','Bérszámfejtési export','attendance','Bér-átadás.',9,ARRAY['attendance_periods']::text[],'{"feature_id": "TA-004", "necessity": "recommended", "value_score": "9", "estimated_dev_cost": "L", "created_in_version": "3.6.0", "current_status": "public"}'::jsonb),
('attendance_audit','Attendance audit','attendance','Compliance.',8,ARRAY['attendance_log']::text[],'{"feature_id": "TA-005", "necessity": "required", "value_score": "8", "estimated_dev_cost": "S", "created_in_version": "3.6.0", "current_status": "public"}'::jsonb),
('attendance_edit_mode','Edit mode + batch drag','attendance','UX gyorsítás.',6,ARRAY['attendance_log']::text[],'{"feature_id": "TA-006", "necessity": "recommended", "value_score": "6", "estimated_dev_cost": "M", "created_in_version": "3.7.1", "current_status": "public"}'::jsonb),
('site_assignment','Telephely beosztás','attendance','Műszak/telephely.',7,ARRAY['offices,attendance_log']::text[],'{"feature_id": "TA-007", "necessity": "recommended", "value_score": "7", "estimated_dev_cost": "M", "created_in_version": "3.7.7", "current_status": "public"}'::jsonb),
('open_api','Open API / Developer Platform','platform','API hozzáférés.',8,ARRAY['workspace_create']::text[],'{"feature_id": "PF-001", "necessity": "optional", "value_score": "8", "estimated_dev_cost": "L", "created_in_version": "3.10.0", "current_status": "public"}'::jsonb),
('payroll_engine','Payroll Integration Engine','platform','Multi-payroll-rendszer.',9,ARRAY['payroll_export']::text[],'{"feature_id": "PF-002", "necessity": "recommended", "value_score": "9", "estimated_dev_cost": "L", "created_in_version": "3.11.0", "current_status": "public"}'::jsonb),
('soc2_iso','SOC2/ISO27001 Security Center','platform','Compliance bizonyíték.',9,ARRAY['audit_log']::text[],'{"feature_id": "PF-003", "necessity": "recommended", "value_score": "9", "estimated_dev_cost": "L", "created_in_version": "3.12.0", "current_status": "public"}'::jsonb),
('feature_flags','Platform Feature Flags','platform','Tier alap.',10,ARRAY['superadmin_control_plane']::text[],'{"feature_id": "PF-004", "necessity": "required", "value_score": "10", "estimated_dev_cost": "M", "created_in_version": "3.13.0", "current_status": "public"}'::jsonb),
('multilingual','5-locale full coverage','platform','EU-coverage.',8,ARRAY['localization']::text[],'{"feature_id": "PF-005", "necessity": "recommended", "value_score": "8", "estimated_dev_cost": "M", "created_in_version": "3.14.0", "current_status": "public"}'::jsonb),
('ai_smart_schedule','Smart Schedule (AI javaslatok)','ai','AI-asszisztens.',8,ARRAY['calendar_monthly,leave_quotas']::text[],'{"feature_id": "AI-001", "necessity": "optional", "value_score": "8", "estimated_dev_cost": "L", "created_in_version": "3.9.0", "current_status": "beta"}'::jsonb),
('ai_burnout_predict','Burnout predikció','ai','Wellbeing forecast.',7,ARRAY['attendance_log,leave_my_view']::text[],'{"feature_id": "AI-002", "necessity": "optional", "value_score": "7", "estimated_dev_cost": "L", "created_in_version": "3.9.0", "current_status": "beta"}'::jsonb),
('ai_chat_assist','Chat asszisztens (Slack/Teams slash cmd)','ai','Asszisztens csatorna.',7,ARRAY['ms365_calendar_sync']::text[],'{"feature_id": "AI-003", "necessity": "optional", "value_score": "7", "estimated_dev_cost": "L", "created_in_version": "3.16.0", "current_status": "planned"}'::jsonb)
ON CONFLICT (feature_key) DO UPDATE SET name=EXCLUDED.name, module=EXCLUDED.module, description=EXCLUDED.description, fiscal_weight=EXCLUDED.fiscal_weight, dependencies=EXCLUDED.dependencies, metadata=EXCLUDED.metadata;