// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isNativeRuntime } from '@/lib/platform/mobile';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from '@/config/publicRuntime';
import {
  SUPABASE_AUTH_STORAGE_KEY,
  supabaseAuthLock,
  supabaseAuthStorage,
} from '@/lib/platform/nativeAuthStorage';

const nativeRuntime = isNativeRuntime();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: supabaseAuthStorage,
    storageKey: SUPABASE_AUTH_STORAGE_KEY,
    ...(supabaseAuthLock ? { lock: supabaseAuthLock } : {}),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: !nativeRuntime,
    flowType: nativeRuntime ? 'pkce' : 'implicit',
  }
});
