/**
 * RFC 4180-compliant CSV parser supporting:
 * - UTF-8 BOM detection
 * - Quoted fields with embedded commas, quotes, and newlines
 * - CRLF and LF line endings
 *
 * Returns headers (string[]) and data rows (string[][]).
 */
export interface ParsedFile {
  headers: string[];
  rows: string[][];
  detectedFormat: 'csv' | 'xls-xml' | 'xlsx';
}

export function parseCSV(text: string): { headers: string[]; rows: string[][] } {
  // Strip UTF-8 BOM
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);

  const records: string[][] = [];
  let current: string[] = [];
  let cell = '';
  let inQuotes = false;
  let i = 0;

  while (i < text.length) {
    const ch = text[i];

    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          cell += '"';
          i += 2;
          continue;
        }
        inQuotes = false;
        i++;
        continue;
      }
      cell += ch;
      i++;
      continue;
    }

    if (ch === '"') {
      inQuotes = true;
      i++;
      continue;
    }
    if (ch === ',') {
      current.push(cell);
      cell = '';
      i++;
      continue;
    }
    if (ch === '\r' && text[i + 1] === '\n') {
      current.push(cell);
      records.push(current);
      current = [];
      cell = '';
      i += 2;
      continue;
    }
    if (ch === '\n' || ch === '\r') {
      current.push(cell);
      records.push(current);
      current = [];
      cell = '';
      i++;
      continue;
    }
    cell += ch;
    i++;
  }
  if (cell.length > 0 || current.length > 0) {
    current.push(cell);
    records.push(current);
  }

  // Drop blank trailing rows
  const filtered = records.filter(r => r.some(c => c.trim() !== ''));
  if (filtered.length === 0) return { headers: [], rows: [] };

  const headers = filtered[0].map(h => h.trim());
  const rows = filtered.slice(1);
  return { headers, rows };
}

/**
 * Parses Excel XML format (the .xls files generated by ExportCenter).
 * Detects <Row><Cell><Data>value</Data></Cell></Row> patterns.
 */
export function parseExcelXml(text: string): { headers: string[]; rows: string[][] } {
  // Strip BOM
  if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);

  const records: string[][] = [];
  const rowMatches = text.matchAll(/<Row[^>]*>([\s\S]*?)<\/Row>/gi);
  for (const rowMatch of rowMatches) {
    const cellsXml = rowMatch[1];
    const cells: string[] = [];
    const cellMatches = cellsXml.matchAll(/<Cell[^>]*>[\s\S]*?<Data[^>]*>([\s\S]*?)<\/Data>[\s\S]*?<\/Cell>/gi);
    for (const cm of cellMatches) {
      const raw = cm[1] || '';
      const decoded = raw
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&apos;/g, "'")
        .replace(/&amp;/g, '&');
      cells.push(decoded);
    }
    if (cells.length > 0) records.push(cells);
  }

  if (records.length === 0) return { headers: [], rows: [] };
  const headers = records[0].map(h => h.trim());
  const rows = records.slice(1).filter(r => r.some(c => c.trim() !== ''));
  return { headers, rows };
}

/**
 * Auto-detects format by content sniffing and parses.
 * Recognized: .csv (RFC 4180), .xls (Excel XML — what ExportCenter generates).
 * Real .xlsx (Open XML zip) is NOT supported in browser without a library;
 * users must export from Excel as CSV for round-trip.
 */
export async function parseUploadedFile(file: File): Promise<ParsedFile> {
  const text = await file.text();
  const fileName = file.name.toLowerCase();

  // Detect Excel XML by content prefix or by .xls extension
  if (text.trimStart().startsWith('<?xml') || /<Workbook[\s>]/i.test(text.slice(0, 500))) {
    const parsed = parseExcelXml(text);
    return { ...parsed, detectedFormat: 'xls-xml' };
  }

  if (fileName.endsWith('.xlsx')) {
    throw new Error(
      'Native .xlsx (Open XML zip) format is not supported for import. ' +
      'Please save the file as CSV or XML Spreadsheet (.xls) in Excel, or use the downloaded template.'
    );
  }

  const parsed = parseCSV(text);
  return { ...parsed, detectedFormat: 'csv' };
}

// ===== File Generation =====

function csvEscape(value: string): string {
  // Neutralize spreadsheet formulas before RFC 4180 escaping.
  if (/^(?:[\t\r]| *[=+@-])/u.test(value)) value = `'${value}`;
  return /[",\r\n]/u.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

export function generateCSV(headers: string[], rows: string[][]): string {
  const BOM = '﻿';
  const lines = [headers.map(csvEscape).join(',')];
  for (const r of rows) {
    lines.push(r.map(csvEscape).join(','));
  }
  return BOM + lines.join('\r\n');
}

function xmlEscape(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Generates Excel XML Spreadsheet 2003 format (.xls).
 * Excel opens this directly. Supports styled headers and a guidance row.
 *
 * @param headers Machine-key column headers
 * @param rows Data rows
 * @param options Style options for the header and optional guidance row
 */
export function generateExcelXML(
  headers: string[],
  rows: string[][],
  options?: {
    requiredFlags?: boolean[];     // mark column as required (yellow header)
    guidanceRow?: string[];        // optional guidance/example row
    sheetName?: string;
  }
): string {
  const sheetName = (options?.sheetName || 'Export').replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 31);
  const required = options?.requiredFlags || headers.map(() => false);

  const styles = `
  <Styles>
    <Style ss:ID="hdrReq"><Font ss:Bold="1"/><Interior ss:Color="#FFE699" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style>
    <Style ss:ID="hdrOpt"><Font ss:Bold="1"/><Interior ss:Color="#DDEBF7" ss:Pattern="Solid"/><Borders><Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/></Borders></Style>
    <Style ss:ID="guide"><Font ss:Italic="1" ss:Color="#666666"/><Interior ss:Color="#F2F2F2" ss:Pattern="Solid"/></Style>
  </Styles>`;

  const headerCells = headers
    .map((h, i) => `<Cell ss:StyleID="${required[i] ? 'hdrReq' : 'hdrOpt'}"><Data ss:Type="String">${xmlEscape(h)}</Data></Cell>`)
    .join('');

  const guidanceRow = options?.guidanceRow
    ? `<Row>${options.guidanceRow.map(g => `<Cell ss:StyleID="guide"><Data ss:Type="String">${xmlEscape(g)}</Data></Cell>`).join('')}</Row>`
    : '';

  const dataRows = rows
    .map(r => `<Row>${r.map(c => `<Cell><Data ss:Type="String">${xmlEscape(c ?? '')}</Data></Cell>`).join('')}</Row>`)
    .join('\n');

  const columns = headers.map(() => '<Column ss:Width="140"/>').join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${styles}
<Worksheet ss:Name="${xmlEscape(sheetName)}">
<Table>
${columns}
<Row>${headerCells}</Row>
${guidanceRow}
${dataRows}
</Table>
</Worksheet>
</Workbook>`;
}

export function downloadFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}
